spring: 
  datasource: 
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/main/resources/db/dins.db

mybatis: 
  type-aliases-package: com.pengfu.entity
  configuration:
    map-underscore-to-camel-case: true